sudo: false
language: ruby
rvm:
  - 2.2
  - 2.4
before_install:
  - git clone https://github.com/smartsheet-platform/smartsheet-sdk-tests.git
  - smartsheet-sdk-tests/travis_scripts/install_wiremock.sh
  - gem install bundler -v 1.15.4

script:
  - smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
  - rake test
